name: Dynamicpvp
version: ${project.version}
main: net.gakiteri.dynamicpvp.Dynamicpvp
api-version: 1.15
authors: [Gakiteri]
commands:
  pvp:
    description: Toggle a players PVP settings
    usage: /<command> [on|off|status] [Player]
