name: Dynamicpvp
version: ${project.version}
main: net.gakiteri.dynamicpvp.Dynamicpvp
api-version: 1.15
authors: [Gakiteri,FoxkDev]
depend: [WorldGuard]
commands:
  pvp:
    description: Toggle a players PVP settings
    usage: /<command> [on|off|status] [Player]
  pvpregion:
    description: Set regions to toggle PVP settings
    usage: /<command> [list|add|remove] [Region]
permissions:
  dynamic.pvp.*:
    description:  Give acces to all commands
    children:
      dynamic.pvp.set: op
      dynamic.pvp.status.players: op
      dynamic.pvp.set.players: op
      dynamic.pvp.set.inworld: op
      dynamic.pvp.region: op
  dynamic.pvp.set:
     description: Set Pvp
     default: op
  dynamic.pvp.set.players:
     description:  Set Pvp to other players
     default: op
  dynamic.pvp.set.inworld:
    description: Set Pvp in all world
    default: op
  dynamic.pvp.status.players:
     description: Get Status from players
     default: op
  dynamic.pvp.region:
    description: Set regions to toogle PVP
    default: op

